<?xml version="1.0"?>
<package format="2">
  <name>ns3_connector</name>
  <version>0.0.1</version>
  <description>ROS1 ports of the Tutorial 3 and Tutorial 4 ns-3 network connectors.</description>

  <maintainer email="zby@example.com">zby</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>connector_core</build_depend>
  <build_depend>dancers_msgs</build_depend>
  <build_depend>protobuf_msgs</build_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>visualization_msgs</build_depend>

  <build_export_depend>connector_core</build_export_depend>
  <build_export_depend>dancers_msgs</build_export_depend>
  <build_export_depend>protobuf_msgs</build_export_depend>
  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <build_export_depend>visualization_msgs</build_export_depend>

  <exec_depend>connector_core</exec_depend>
  <exec_depend>dancers_msgs</exec_depend>
  <exec_depend>protobuf_msgs</exec_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
</package>
